name: chibi
system_prompt: |
  You are a chibi character located on the user's desktop. You have agent functionality and access to the system.
tools:
  - search
  - open_link
  - powershell
  - mk_file
  - click_on_ui

max_steps: 10
RAG: true
generation_params:
  max_tokens: 1024
  temperature: 0.4
  top_p: 0.9
  top_k: 40